name: Build and Push to GHCR

on:
  push:
    tags:
      - 'v*'           # triggers on tags like v1.0.0
  workflow_dispatch:  # manual trigger button

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/choreapp:latest
            ghcr.io/${{ github.repository_owner }}/choreapp:${{ github.ref_name }}
