name: Build and Push to GHCR

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Node image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: node-server/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/choreapp-node:latest
            ghcr.io/${{ github.repository_owner }}/choreapp-node:${{ github.ref_name }}

  build-ocr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push OCR image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ocr-server/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/choreapp-ocr:latest
            ghcr.io/${{ github.repository_owner }}/choreapp-ocr:${{ github.ref_name }}
